name: streamlit
channels:
  - plotly
  - defaults
dependencies:
  - python=3.10
  - scikit-learn
  - pandas
  - seaborn
  - matplotlib
  - plotly
  - pip
  - pip:
    - streamlit==1.7.0
    - click==8.0.4
    - colormap
    - easydev
