"""A setuptools based setup module. Setup configuration is read from setup.cfg.

This file autogenerated from cookiecutter template python-cookiecutter-template
TEMPLATE VERSION: 1.0.0
TEMPLATE URL: http://github.com/hummel/python-minimal-cookiecutter

For a detailed explanation of setup options see:
https://packaging.python.org/en/latest/distributing.html
https://github.com/pypa/sampleproject
setuptools.readthedocs.io
"""
import os
from os.path import basename, splitext
from glob import glob
from setuptools import setup, find_packages
from setuptools.config import read_configuration


def grab_version():
    here = os.path.abspath(os.path.dirname(__file__))
    config = read_configuration(os.path.join(here, "setup.cfg"))
    print("Version:", config["metadata"]["version"])


# Run setup.
if __name__ == "__main__":
    grab_version()
    setup(
        packages=find_packages("src"),
        package_dir={"": "src"},
        py_modules=[splitext(basename(path))[0] for path in glob("src/*.py")],
    )
